"""Rename password column to hashed_password

Revision ID: 2919ec7da54c
Revises: 2c751d5836b1
Create Date: 2025-02-03 11:01:40.475621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2919ec7da54c'
down_revision = '2c751d5836b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.VARCHAR(length=128), nullable=True))

    # ### end Alembic commands ###
