"""Remove is_invited column

Revision ID: 4e961303a7b7
Revises: cfe84e11ca65
Create Date: 2025-02-03 11:59:35.769663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e961303a7b7'
down_revision = 'cfe84e11ca65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=60),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=60),
               existing_nullable=True)
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.TEXT(length=128), nullable=True))
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('hashed_password',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###
