"""Add is_active column to user model

Revision ID: 65761a79bab8
Revises: f56a7385d152
Create Date: 2025-02-01 18:23:43.785791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65761a79bab8'
down_revision = 'f56a7385d152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
